version: '3'
services:
  BANCO_VALNEI_MYSQL:  
    image: mysql:8.0
    container_name: BANCO_MYSQL
    restart: always    
    ports:      
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'banco_valnei'      
      MYSQL_USER: 'user'      
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - valnei-net          
    volumes:
      - mysqldb:/var/lib/mysql
    user: "1000:1000"
volumes:
  mysqldb:
networks:
  valnei-net: