version: '3.7'
services: 
  mongodb_container:  
    image: mongo
    restart: always 
    container_name: BANCO_MONGO
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2023!    
    volumes:      
      - mongodb:/data/db      
    networks:
      - mongo_net

volumes:  
  mongodb:  
networks:
  mongo_net:
    driver: bridge
