version: '3'
services:
  mongo-express:
    image: mongo-express
    container_name: BANCO_MONGO
    restart: always # em caso de falha o conteiner reinicia.
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: valnei
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2023!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2023!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:  
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2023!
    ports:
      - "27017:27017"
    volumes:
      - /home/valnei/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
